/**
 * Minimal, dependency-free PDF writer — enough to render an invoice as a real
 * application/pdf document the browser can open in a new tab (no backend, per
 * the brief). ASCII only, so byte offsets equal string offsets for the xref.
 */

export interface InvoicePdfData {
  id: string;
  status: string;
  contractor: string;
  role: string;
  destination: string;
  amount: string;
  settlement: string;
  method: string;
  issued: string;
  due: string;
  reference: string;
}

function toAscii(s: string) {
  return s.replace(/[^\x20-\x7e]/g, "");
}

function escape(s: string) {
  return toAscii(s).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

export function buildInvoicePdf(data: InvoicePdfData): Blob {
  const lines = [
    `Invoice ${data.id}`,
    `Status: ${data.status}`,
    "",
    `Contractor: ${data.contractor}`,
    `Role: ${data.role}`,
    `Destination: ${data.destination}`,
    "",
    `Amount: ${data.amount}`,
    `Settlement (USD): ${data.settlement}`,
    `Payment method: ${data.method}`,
    "",
    `Issued: ${data.issued}`,
    `Due: ${data.due}`,
    `Settlement reference: ${data.reference}`,
    "",
    "Generated by Global Pay - demo document, no payment processed.",
  ];

  let content = `BT\n/F1 18 Tf\n50 792 Td\n(Global Pay - Invoice) Tj\n/F1 11 Tf\n0 -34 Td\n`;
  lines.forEach((line, i) => {
    if (i > 0) content += "0 -16 Td\n";
    content += `(${escape(line)}) Tj\n`;
  });
  content += "ET";

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((obj, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((off) => {
    pdf += `${String(off).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return new Blob([pdf], { type: "application/pdf" });
}
