/**
 * Deterministic mock invoices — no backend (brief). Shaped like a real
 * cross-border payout ledger: mixed currencies, payment rails, and states.
 * `usdValue` is the settlement-normalized amount platforms report on, so the
 * dashboard can aggregate across currencies honestly.
 */

export type InvoiceStatus = "pending" | "processing" | "paid" | "failed";
export type PaymentMethod = "bank" | "wallet" | "usdc";

export interface Invoice {
  id: string;
  contractor: string;
  title: string;
  country: string;
  amount: number;
  currency: string;
  usdValue: number;
  method: PaymentMethod;
  status: InvoiceStatus;
  /** Issue date, ISO yyyy-mm-dd. */
  date: string;
  /** Due date, ISO yyyy-mm-dd. Failed/crypto rows may not have one. */
  dueDate?: string;
}

export const STATUS_LABELS: Record<InvoiceStatus, string> = {
  pending: "Pending",
  processing: "Processing",
  paid: "Paid",
  failed: "Failed",
};

export const METHOD_LABELS: Record<PaymentMethod, string> = {
  bank: "Bank Transfer",
  wallet: "Wallet",
  usdc: "USDC",
};

export const invoices: Invoice[] = [
  {
    id: "INV-2026-0152",
    contractor: "Chen Wei",
    title: "ML Engineer",
    country: "Singapore",
    amount: 4100,
    currency: "SGD",
    usdValue: 3050,
    method: "bank",
    status: "pending",
    date: "2026-07-08",
    dueDate: "2026-07-22",
  },
  {
    id: "INV-2026-0151",
    contractor: "Elena Vasquez",
    title: "Accountant",
    country: "Mexico",
    amount: 38500,
    currency: "MXN",
    usdValue: 2075,
    method: "bank",
    status: "pending",
    date: "2026-07-08",
    dueDate: "2026-07-22",
  },
  {
    id: "INV-2026-0150",
    contractor: "Tom Nguyen",
    title: "Fullstack Developer",
    country: "Vietnam",
    amount: 2200,
    currency: "USD",
    usdValue: 2200,
    method: "wallet",
    status: "pending",
    date: "2026-07-07",
    dueDate: "2026-07-21",
  },
  {
    id: "INV-2026-0149",
    contractor: "Fatima Al-Rashid",
    title: "Technical Writer",
    country: "UAE",
    amount: 5900,
    currency: "AED",
    usdValue: 1605,
    method: "bank",
    status: "pending",
    date: "2026-07-07",
    dueDate: "2026-07-21",
  },
  {
    id: "INV-2026-0148",
    contractor: "Lucas Costa",
    title: "Backend Developer",
    country: "Brazil",
    amount: 11800,
    currency: "BRL",
    usdValue: 2185,
    method: "wallet",
    status: "pending",
    date: "2026-06-16",
    dueDate: "2026-06-30",
  },
  {
    id: "INV-2026-0147",
    contractor: "Ines Silva",
    title: "UX Researcher",
    country: "Portugal",
    amount: 1680,
    currency: "EUR",
    usdValue: 1820,
    method: "bank",
    status: "pending",
    date: "2026-06-16",
    dueDate: "2026-06-30",
  },
  {
    id: "INV-2026-0146",
    contractor: "Daniel Kim",
    title: "Mobile Developer",
    country: "South Korea",
    amount: 2750,
    currency: "USD",
    usdValue: 2750,
    method: "usdc",
    status: "pending",
    date: "2026-06-14",
    dueDate: "2026-06-28",
  },
  {
    id: "INV-2026-0145",
    contractor: "Sofia Petrova",
    title: "Data Analyst",
    country: "Bulgaria",
    amount: 1980,
    currency: "EUR",
    usdValue: 2145,
    method: "bank",
    status: "pending",
    date: "2026-06-14",
    dueDate: "2026-06-28",
  },
  {
    id: "INV-2026-0144",
    contractor: "Lucia Moreau",
    title: "Content Strategist",
    country: "France",
    amount: 1450,
    currency: "EUR",
    usdValue: 1570,
    method: "wallet",
    status: "pending",
    date: "2026-06-12",
    dueDate: "2026-06-26",
  },
  {
    id: "INV-2026-0143",
    contractor: "Yuki Tanaka",
    title: "QA Engineer",
    country: "Japan",
    amount: 310000,
    currency: "JPY",
    usdValue: 2150,
    method: "bank",
    status: "pending",
    date: "2026-06-12",
    dueDate: "2026-06-26",
  },
  {
    id: "INV-2026-0142",
    contractor: "Priya Sharma",
    title: "Frontend Developer",
    country: "India",
    amount: 185000,
    currency: "INR",
    usdValue: 2220,
    method: "bank",
    status: "pending",
    date: "2026-07-03",
    dueDate: "2026-07-17",
  },
  {
    id: "INV-2026-0141",
    contractor: "Mateo Alvarez",
    title: "Backend Developer",
    country: "Argentina",
    amount: 2400,
    currency: "USD",
    usdValue: 2400,
    method: "wallet",
    status: "pending",
    date: "2026-07-03",
    dueDate: "2026-07-17",
  },
  {
    id: "INV-2026-0140",
    contractor: "Amara Okafor",
    title: "Product Designer",
    country: "Nigeria",
    amount: 1850,
    currency: "USD",
    usdValue: 1850,
    method: "usdc",
    status: "pending",
    date: "2026-07-02",
    dueDate: "2026-07-16",
  },
  {
    id: "INV-2026-0139",
    contractor: "Jonas Weber",
    title: "DevOps Engineer",
    country: "Germany",
    amount: 3200,
    currency: "EUR",
    usdValue: 3465,
    method: "bank",
    status: "pending",
    date: "2026-07-01",
    dueDate: "2026-07-15",
  },
  {
    id: "INV-2026-0138",
    contractor: "Yuki Tanaka",
    title: "QA Engineer",
    country: "Japan",
    amount: 310000,
    currency: "JPY",
    usdValue: 2150,
    method: "bank",
    status: "pending",
    date: "2026-06-30",
    dueDate: "2026-07-14",
  },
  {
    id: "INV-2026-0137",
    contractor: "Lucia Moreau",
    title: "Content Strategist",
    country: "France",
    amount: 1450,
    currency: "EUR",
    usdValue: 1570,
    method: "wallet",
    status: "processing",
    date: "2026-07-09",
    dueDate: "2026-07-23",
  },
  {
    id: "INV-2026-0136",
    contractor: "Harsh Kadam",
    title: "Frontend Developer",
    country: "India",
    amount: 96000,
    currency: "INR",
    usdValue: 1152,
    method: "wallet",
    status: "processing",
    date: "2026-07-08",
    dueDate: "2026-07-22",
  },
  {
    id: "INV-2026-0135",
    contractor: "Sofia Petrova",
    title: "Data Analyst",
    country: "Bulgaria",
    amount: 1980,
    currency: "EUR",
    usdValue: 2145,
    method: "bank",
    status: "processing",
    date: "2026-06-26",
    dueDate: "2026-07-10",
  },
  {
    id: "INV-2026-0134",
    contractor: "Daniel Kim",
    title: "Mobile Developer",
    country: "South Korea",
    amount: 2750,
    currency: "USD",
    usdValue: 2750,
    method: "usdc",
    status: "processing",
    date: "2026-06-25",
    dueDate: "2026-07-09",
  },
  {
    id: "INV-2026-0133",
    contractor: "Ines Silva",
    title: "UX Researcher",
    country: "Portugal",
    amount: 1680,
    currency: "EUR",
    usdValue: 1820,
    method: "bank",
    status: "paid",
    date: "2026-07-06",
    dueDate: "2026-07-09",
  },
  {
    id: "INV-2026-0132",
    contractor: "Mateo Alvarez",
    title: "Backend Developer",
    country: "Argentina",
    amount: 2400,
    currency: "USD",
    usdValue: 2400,
    method: "wallet",
    status: "paid",
    date: "2026-07-05",
    dueDate: "2026-07-08",
  },
  {
    id: "INV-2026-0131",
    contractor: "Chen Wei",
    title: "ML Engineer",
    country: "Singapore",
    amount: 4100,
    currency: "SGD",
    usdValue: 3050,
    method: "bank",
    status: "paid",
    date: "2026-07-04",
    dueDate: "2026-07-07",
  },
  {
    id: "INV-2026-0130",
    contractor: "Amara Okafor",
    title: "Product Designer",
    country: "Nigeria",
    amount: 1850,
    currency: "USD",
    usdValue: 1850,
    method: "usdc",
    status: "paid",
    date: "2026-06-15",
    dueDate: "2026-06-29",
  },
  {
    id: "INV-2026-0129",
    contractor: "Elena Vasquez",
    title: "Accountant",
    country: "Mexico",
    amount: 38500,
    currency: "MXN",
    usdValue: 2075,
    method: "bank",
    status: "paid",
    date: "2026-06-13",
    dueDate: "2026-06-27",
  },
  {
    id: "INV-2026-0128",
    contractor: "Tom Nguyen",
    title: "Fullstack Developer",
    country: "Vietnam",
    amount: 2200,
    currency: "USD",
    usdValue: 2200,
    method: "wallet",
    status: "paid",
    date: "2026-06-12",
    dueDate: "2026-06-26",
  },
  {
    id: "INV-2026-0127",
    contractor: "Priya Sharma",
    title: "Frontend Developer",
    country: "India",
    amount: 185000,
    currency: "INR",
    usdValue: 2220,
    method: "bank",
    status: "paid",
    date: "2026-06-05",
    dueDate: "2026-06-19",
  },
  {
    id: "INV-2026-0126",
    contractor: "Jenny Wang",
    title: "Product Designer",
    country: "Taiwan",
    amount: 0.82,
    currency: "ETH",
    usdValue: 2870,
    method: "usdc",
    status: "failed",
    date: "2026-06-04",
  },
  {
    id: "INV-2026-0125",
    contractor: "Jonas Weber",
    title: "DevOps Engineer",
    country: "Germany",
    amount: 3200,
    currency: "EUR",
    usdValue: 3465,
    method: "bank",
    status: "paid",
    date: "2026-06-03",
    dueDate: "2026-06-17",
  },
  {
    id: "INV-2026-0124",
    contractor: "Fatima Al-Rashid",
    title: "Technical Writer",
    country: "UAE",
    amount: 5900,
    currency: "AED",
    usdValue: 1605,
    method: "bank",
    status: "paid",
    date: "2026-06-01",
    dueDate: "2026-06-15",
  },
  {
    id: "INV-2026-0123",
    contractor: "Lucas Costa",
    title: "Backend Developer",
    country: "Brazil",
    amount: 11800,
    currency: "BRL",
    usdValue: 2185,
    method: "wallet",
    status: "paid",
    date: "2026-05-29",
    dueDate: "2026-06-12",
  },
  {
    id: "INV-2026-0122",
    contractor: "Daniel Kim",
    title: "Mobile Developer",
    country: "South Korea",
    amount: 2750,
    currency: "USD",
    usdValue: 2750,
    method: "usdc",
    status: "paid",
    date: "2026-05-27",
    dueDate: "2026-06-10",
  },
  {
    id: "INV-2026-0121",
    contractor: "Sofia Petrova",
    title: "Data Analyst",
    country: "Bulgaria",
    amount: 1980,
    currency: "EUR",
    usdValue: 2145,
    method: "bank",
    status: "failed",
    date: "2026-05-26",
  },
  {
    id: "INV-2026-0120",
    contractor: "Ines Silva",
    title: "UX Researcher",
    country: "Portugal",
    amount: 1680,
    currency: "EUR",
    usdValue: 1820,
    method: "bank",
    status: "paid",
    date: "2026-05-22",
    dueDate: "2026-06-05",
  },
  {
    id: "INV-2026-0119",
    contractor: "Chen Wei",
    title: "ML Engineer",
    country: "Singapore",
    amount: 4100,
    currency: "SGD",
    usdValue: 3050,
    method: "bank",
    status: "paid",
    date: "2026-05-20",
    dueDate: "2026-06-03",
  },
  {
    id: "INV-2026-0118",
    contractor: "Tom Nguyen",
    title: "Fullstack Developer",
    country: "Vietnam",
    amount: 2200,
    currency: "USD",
    usdValue: 2200,
    method: "wallet",
    status: "paid",
    date: "2026-05-15",
    dueDate: "2026-05-29",
  },
  {
    id: "INV-2026-0117",
    contractor: "Mateo Alvarez",
    title: "Backend Developer",
    country: "Argentina",
    amount: 2400,
    currency: "USD",
    usdValue: 2400,
    method: "wallet",
    status: "processing",
    date: "2026-05-14",
    dueDate: "2026-05-28",
  },
  {
    id: "INV-2026-0116",
    contractor: "Priya Sharma",
    title: "Frontend Developer",
    country: "India",
    amount: 185000,
    currency: "INR",
    usdValue: 2220,
    method: "bank",
    status: "processing",
    date: "2026-05-12",
    dueDate: "2026-05-26",
  },
  {
    id: "INV-2026-0115",
    contractor: "Amara Okafor",
    title: "Product Designer",
    country: "Nigeria",
    amount: 1850,
    currency: "USD",
    usdValue: 1850,
    method: "usdc",
    status: "paid",
    date: "2026-05-10",
    dueDate: "2026-05-24",
  },
  {
    id: "INV-2026-0114",
    contractor: "Jonas Weber",
    title: "DevOps Engineer",
    country: "Germany",
    amount: 3200,
    currency: "EUR",
    usdValue: 3465,
    method: "bank",
    status: "paid",
    date: "2026-05-08",
    dueDate: "2026-05-22",
  },
  {
    id: "INV-2026-0113",
    contractor: "Harsh Kadam",
    title: "Frontend Developer",
    country: "India",
    amount: 96000,
    currency: "INR",
    usdValue: 1152,
    method: "wallet",
    status: "paid",
    date: "2026-05-06",
    dueDate: "2026-05-20",
  },
  {
    id: "INV-2026-0112",
    contractor: "Chen Wei",
    title: "ML Engineer",
    country: "Singapore",
    amount: 4100,
    currency: "SGD",
    usdValue: 3050,
    method: "bank",
    status: "failed",
    date: "2026-05-04",
  },
  {
    id: "INV-2026-0111",
    contractor: "Tom Nguyen",
    title: "Fullstack Developer",
    country: "Vietnam",
    amount: 2200,
    currency: "USD",
    usdValue: 2200,
    method: "wallet",
    status: "paid",
    date: "2026-05-02",
    dueDate: "2026-05-16",
  },
  {
    id: "INV-2026-0110",
    contractor: "Elena Vasquez",
    title: "Accountant",
    country: "Mexico",
    amount: 38500,
    currency: "MXN",
    usdValue: 2075,
    method: "bank",
    status: "processing",
    date: "2026-04-30",
    dueDate: "2026-05-14",
  },
];

export function getInvoice(id: string) {
  return invoices.find((invoice) => invoice.id === id);
}

/** Distinct contractors, for filters and the payout dialog. */
export function getContractors() {
  return [...new Set(invoices.map((i) => i.contractor))].sort();
}

export interface ContractorProfile {
  name: string;
  title: string;
  country: string;
  /** Currency this contractor has historically been paid in. */
  currency: string;
  /** Rail they were last paid over, used to preselect the payout method. */
  method: PaymentMethod;
}

/**
 * Contractor roster derived from their most recent invoice — the payout flow
 * needs title/country/currency per person, not just a name. Ledger rows are
 * the only source of contractor identity here (no backend), so "most recent
 * invoice wins" keeps the profile consistent with what the table shows.
 */
export function getContractorProfiles(): ContractorProfile[] {
  const latest = new Map<string, Invoice>();
  for (const invoice of invoices) {
    const seen = latest.get(invoice.contractor);
    if (!seen || invoice.date > seen.date) latest.set(invoice.contractor, invoice);
  }

  return [...latest.values()]
    .map((invoice) => ({
      name: invoice.contractor,
      title: invoice.title,
      country: invoice.country,
      currency: invoice.currency,
      method: invoice.method,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function getContractorProfile(name: string) {
  return getContractorProfiles().find((profile) => profile.name === name);
}
